import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RotatingBadge from "@/components/RotatingBadge";
import { ScrollProvider } from "@/components/ScrollProvider"; // import the provider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",            // default favicon
    apple: "/apple-touch-icon.png",  // iOS home screen icon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* PNG favicons for different sizes */}
        <link rel="icon" type="image/png" sizes="16x16" href="/jaegermeister-16.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/jaegermeister-32.png" />
        <link rel="icon" type="image/png" sizes="48x48" href="/jaegermeister-48.png" />

        {/* Apple touch icon for iOS */}
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#244034] text-white min-h-screen flex flex-col`}
      >
        <ScrollProvider>
          <main className="flex-grow">{children}</main>
          {/* Render the rotating badge globally */}
          <RotatingBadge />
        </ScrollProvider>
      </body>
    </html>
  );
}
